<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <AssemblyName>KeyLine</AssemblyName>
        <Product>KeyLine</Product>
        <AssemblyTitle>KeyLine</AssemblyTitle>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
        <NoWarn>$(NoWarn);WFO0003</NoWarn>
        <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <Version>1.6.1</Version>
        <AssemblyVersion>1.6.1.0</AssemblyVersion>
        <FileVersion>1.6.1.0</FileVersion>
        <InformationalVersion>1.6.1</InformationalVersion>
    </PropertyGroup>

    <ItemGroup>
        <Using Remove="System.Windows.Forms"/>
        <Using Remove="System.Drawing"/>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Assets\AppIcon.ico"/>
        <Resource Include="Assets\TitleLogo.png"/>
    </ItemGroup>

    <ItemGroup>
        <Page Update="UI\TextInput\TextInputWindow.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\MainWindow\MainWindow.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\Common\EntryBlocks\NumberEntryBlock.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\Common\EntryBlocks\PagerEntryBlock.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\Common\EntryBlocks\TimeEntryBlock.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\Common\EntryBlocks\MultiValueEntryBlock.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\Common\EntryBlocks\OptionsPillBlock.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\Common\Styles\Buttons.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
        <Page Update="UI\Common\Styles\CheckBoxes.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
        <Page Update="UI\Common\Styles\Colors.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
        <Page Update="UI\Common\Styles\ComboBoxes.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
        <Page Update="UI\Common\Styles\Options.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
        <Page Update="UI\Common\Styles\ScrollBars.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
        <Page Update="UI\Common\Styles\TextBlocks.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
        <Page Update="UI\Common\Styles\TextBoxes.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
        <Page Update="UI\Common\Styles\ToolTips.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
        <Page Update="UI\Nodes\AddNode.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\Nodes\DelayNode.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\Nodes\KeyNode.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\Nodes\BackgroundMouseNode.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\Nodes\TextNode.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\Nodes\MouseNode.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\Inspector\InspectorWindow.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\Settings\SettingsView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\ImportExport\ImportConfirmationView.xaml">
          <Generator>MSBuild:Compile</Generator>
          <XamlRuntime>Wpf</XamlRuntime>
          <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\ImportExport\ExportMacroSelectionView.xaml">
          <Generator>MSBuild:Compile</Generator>
          <XamlRuntime>Wpf</XamlRuntime>
          <SubType>Designer</SubType>
        </Page>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Services\Edit\"/>
    </ItemGroup>

</Project>
